function Word(){;
    print(" ");
    $word;
    gets($word);
};
function Sort(){;
    $sort=select("../files/project/button/sorts.js");
};
;
function Trans(){;
    print(" ");
    $def=gets();
};
;
function Reset(){;
    strclr($sort);
    strclr($def);
};
;
function ResetAll(){;
    strclr($sort);
    strclr($def);
    strclr(buf);
    remove("buf.dat");
    remove("out.dat");
};
;
function AddDef(){;
    fputs(",","buf.dat","a");
    fputs($sort,"buf.dat","a");
    fputs("@","buf.dat","a");
    fputs($def,"buf.dat","a");
    fputs(";","buf.dat","a");
    strclr($sort);
    strclr($def);
};
;
function AddAllDef(){;
    var buf=fgets("buf.dat");
    remove("out.dat");
    fputs(buf,"out.dat","w");
    remove("buf.dat");//remove buf file;
};
;
function PrintAllDef(){;
    print(buf);
    char=getch();
};
;
function PrintAllData(){;
    showalldata();
};
;
;