function InitArrayByDeclaration(){;
    var s[2][3]={1,2,3,4,5,6};
    print("s = ");
    for(i=0;i<2;++i){;
        for(j=0;j<3;++j){;
            print(s[i][j]);
            print(" ");
        };
    };
    getch();
};
;
function InitArrayByLoop1(){;
    var arr[3][4];
    var k=1;
    print("arr = ");
    for(i=0;i<3;++i){;
        for(j=0;j<4;++j){;
            arr[i][j]=k;
            k=k*2;
        };
    };
    for(i=0;i<3;++i){;
        for(j=0;j<4;++j){;
            print(arr[i][j]);
            print(" ");
        };
    };
    getch();
};
;
function InitArrayByLoop2(){;
    var arr[2][3];
    print("arr = ");
    for(i=0;i<2;++i){;
        for(j=0;j<3;++j){;
            arr[i][j]=(i+1)*(j+1);
            print(arr[i][j]);
            print(" ");
        };
    };
    getch();
};
;
function temp_print_all_data(){;
    printAllData();
};
;
function getObject(name,number){;
    var object="object";
    var object.name=name;
    var object.number=number;
    return object;
};
;
function copyObject(object){;
    var another_object=object;
    return another_object;
};
;
function CreateClass(){;
    var name;
    print("input name");
    name=gets();
    print("input number");
    gets(number);
;
    print("creating object...\n");
    object=getObject(name,number);
;
    print("object.name=");
    print(object.name);
    print("\nobject.number=");
    print(object.number);
    getch();
};
;
function testPrint(){;
   print("1"+1);print("\n");
   print(1+1);print("\n");
   print('1'+1);print("\n");
   print("1"+1+1);print("\n");
};
;