#include "find/all.cpp"
#include "Clause/ClauseCheck.cpp"
#include "Conj/ConjCheck.cpp"
#include "WOC1/all.cpp"//�Z��
#include "SWS1/all.cpp"//�Ɇ�
#include "SWS2/all.cpp"//���~
#include "SWS3/all.cpp"//���Z
#include "Framework/all.cpp"
#include "Framework.cpp"
